name: Modify Frontend URLs

on:
  push:
    branches:
      - master

jobs:
  modify-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Debug - List Directory Contents
      run: ls -al

    - name: Debug - Print Working Directory
      run: pwd

    - name: Modify URLs
      run: |
        # Replace "https://" with "http://" in your frontend code
        sed -i 's|https://3.111.187.209:8000/|http://3.111.187.209:8000/|g' index.html

    - name: Commit changes
      run: |
        git config --global user.name 'jhon-patel'
        git config --global user.email 'parthpatelaa19@gmail.com'
        git add .
        git commit -m 'Update backend URLs to use HTTP'
        git push
